"""
Master competitor registry for [Company] CI Bot.
All collectors and processors source competitor metadata from here.
"""

COMPETITORS: dict[str, dict] = {
    # ----------------------------------------------------------------
    # Padel Analytics / Court Tech
    # ----------------------------------------------------------------
    "plasight": {
        "name": "PlaySight",
        "sport": ["padel"],
        "tier": "direct",
        "website": "https://plasight.com",
        "pricing_url": "https://plasight.com/pricing",
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": "plasight",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["plasight", "pla sight"],
        "twitter_handle": "plasight",
        "news_keywords": ["PlaySight", "PlaySight padel AI", "PlaySight video analytics"],
        "active": True,
    },
    "wingfield": {
        "name": "Wingfield",
        "sport": ["padel", "tennis"],
        "tier": "direct",
        "website": "https://wingfield.io",
        "pricing_url": "https://wingfield.io/pricing",
        "app_store_id": None,
        "play_store_id": "com.wingfield",
        "linkedin_company": "wingfield",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["wingfield"],
        "twitter_handle": "wingfield_io",
        "news_keywords": ["Wingfield padel", "Wingfield tennis analytics"],
        "active": True,
    },
    "padel_manager": {
        "name": "PadelManager",
        "sport": ["padel"],
        "tier": "adjacent",
        "website": "https://padelmanager.com",
        "pricing_url": "https://padelmanager.com/pricing",
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": "padelmanager",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["padelmanager", "padel manager"],
        "twitter_handle": None,
        "news_keywords": ["PadelManager"],
        "active": True,
    },
    "playtomic": {
        "name": "Playtomic",
        "sport": ["padel", "tennis", "pickleball"],
        "tier": "adjacent",
        "website": "https://playtomic.io",
        "pricing_url": "https://playtomic.io/pricing",
        "app_store_id": "1192712953",
        "play_store_id": "com.playtomic",
        "linkedin_company": "playtomic",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["playtomic"],
        "twitter_handle": "playtomic",
        "news_keywords": ["Playtomic funding", "Playtomic analytics", "Playtomic padel"],
        "active": True,
    },
    "setpro": {
        "name": "SetPro",
        "sport": ["padel"],
        "tier": "direct",
        "website": "https://setpro.app",
        "pricing_url": "https://setpro.app",
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": "setpro",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["setpro", "set pro padel"],
        "twitter_handle": None,
        "news_keywords": ["SetPro padel analytics"],
        "active": True,
    },
    "padel_intelligence": {
        "name": "Padel Intelligence",
        "sport": ["padel"],
        "tier": "direct",
        "website": "https://padelintelligence.com",
        "pricing_url": "https://padelintelligence.com",
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": None,
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["padel intelligence"],
        "twitter_handle": None,
        "news_keywords": ["Padel Intelligence analytics"],
        "active": True,
    },
    "padel_guru": {
        "name": "PadelGuru",
        "sport": ["padel"],
        "tier": "adjacent",
        "website": "https://padelguru.com",
        "pricing_url": None,
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": None,
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["padelguru", "padel guru"],
        "twitter_handle": None,
        "news_keywords": ["PadelGuru"],
        "active": True,
    },
    "tech_padel": {
        "name": "TechPadel",
        "sport": ["padel"],
        "tier": "direct",
        "website": "https://techpadel.com",
        "pricing_url": None,
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": None,
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["techpadel", "tech padel"],
        "twitter_handle": None,
        "news_keywords": ["TechPadel AI"],
        "active": True,
    },
    "padel_pro_cam": {
        "name": "Padel Pro Cam",
        "sport": ["padel"],
        "tier": "direct",
        "website": "https://padelprocam.com",
        "pricing_url": None,
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": None,
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["padel pro cam", "padelprocam"],
        "twitter_handle": None,
        "news_keywords": ["Padel Pro Cam"],
        "active": False,  # Verify this exists
    },
    "padelstats": {
        "name": "PadelStats",
        "sport": ["padel"],
        "tier": "direct",
        "website": "https://padelstats.com",
        "pricing_url": None,
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": None,
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["padelstats", "padel stats"],
        "twitter_handle": None,
        "news_keywords": ["PadelStats"],
        "active": True,
    },

    # ----------------------------------------------------------------
    # Pickleball Analytics / Tech
    # ----------------------------------------------------------------
    "swingvision": {
        "name": "SwingVision",
        "sport": ["pickleball", "tennis"],
        "tier": "direct",
        "website": "https://swingvision.com",
        "pricing_url": "https://swingvision.com/pricing",
        "app_store_id": "1455351179",
        "play_store_id": None,
        "linkedin_company": "swingvision",
        "greenhouse_slug": None,
        "rss_feeds": ["https://swingvision.com/blog/rss"],
        "reddit_mentions": ["swingvision", "swing vision"],
        "twitter_handle": "swingvision_app",
        "news_keywords": ["SwingVision funding", "SwingVision pickleball", "SwingVision AI"],
        "active": True,
    },
    "dupr": {
        "name": "DUPR",
        "sport": ["pickleball"],
        "tier": "adjacent",
        "website": "https://mydupr.com",
        "pricing_url": "https://mydupr.com/pricing",
        "app_store_id": "1561515030",
        "play_store_id": None,
        "linkedin_company": "dupr",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["dupr", "DUPR rating", "dynamic universal pickleball rating"],
        "twitter_handle": "DUPRpickleball",
        "news_keywords": ["DUPR pickleball rating", "DUPR funding"],
        "active": True,
    },
    "pickleplay": {
        "name": "PicklePlay",
        "sport": ["pickleball"],
        "tier": "adjacent",
        "website": "https://pickleplay.com",
        "pricing_url": "https://pickleplay.com/pricing",
        "app_store_id": "1592065078",
        "play_store_id": None,
        "linkedin_company": "pickleplay",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["pickleplay", "pickle play"],
        "twitter_handle": "pickleplayapp",
        "news_keywords": ["PicklePlay app pickleball"],
        "active": True,
    },
    "dink": {
        "name": "Dink",
        "sport": ["pickleball"],
        "tier": "adjacent",
        "website": "https://thedinkpickleball.com",
        "pricing_url": None,
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": "the-dink",
        "greenhouse_slug": None,
        "rss_feeds": ["https://thedinkpickleball.com/feed"],
        "reddit_mentions": ["the dink pickleball", "dink pickleball"],
        "twitter_handle": "thedinkpb",
        "news_keywords": ["The Dink pickleball media"],
        "active": True,
    },
    "pb_vision": {
        "name": "PB Vision",
        "sport": ["pickleball"],
        "tier": "direct",
        "website": "https://pbvision.com",
        "pricing_url": "https://pbvision.com/pricing",
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": None,
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["pb vision", "pbvision", "pickleball vision AI"],
        "twitter_handle": None,
        "news_keywords": ["PB Vision pickleball analytics"],
        "active": True,
    },
    "selkirk_analytics": {
        "name": "Selkirk Analytics",
        "sport": ["pickleball"],
        "tier": "adjacent",
        "website": "https://selkirk.com",
        "pricing_url": None,
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": "selkirk-sport",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["selkirk analytics", "selkirk ai"],
        "twitter_handle": "SelkirkSport",
        "news_keywords": ["Selkirk analytics pickleball", "Selkirk AI"],
        "active": True,
    },
    "rallyst": {
        "name": "Rallyst",
        "sport": ["pickleball", "padel", "tennis"],
        "tier": "direct",
        "website": "https://rallyst.com",
        "pricing_url": None,
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": None,
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["rallyst"],
        "twitter_handle": None,
        "news_keywords": ["Rallyst sports analytics"],
        "active": True,
    },

    # ----------------------------------------------------------------
    # Cross-sport / Multi-racquet
    # ----------------------------------------------------------------
    "coachnow": {
        "name": "CoachNow",
        "sport": ["tennis", "padel", "pickleball"],
        "tier": "adjacent",
        "website": "https://coachnow.io",
        "pricing_url": "https://coachnow.io/pricing",
        "app_store_id": "895668146",
        "play_store_id": None,
        "linkedin_company": "coachnow",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["coachnow"],
        "twitter_handle": "CoachNowApp",
        "news_keywords": ["CoachNow sports coaching app", "CoachNow funding"],
        "active": True,
    },
    "dartfish": {
        "name": "Dartfish",
        "sport": ["tennis", "padel", "pickleball", "multi-sport"],
        "tier": "adjacent",
        "website": "https://dartfish.com",
        "pricing_url": "https://dartfish.com/pricing",
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": "dartfish",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["dartfish"],
        "twitter_handle": "Dartfish",
        "news_keywords": ["Dartfish video analysis sports"],
        "active": True,
    },
    "sportos": {
        "name": "SportOS",
        "sport": ["padel", "tennis"],
        "tier": "adjacent",
        "website": "https://sportos.io",
        "pricing_url": None,
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": "sportos",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["sportos"],
        "twitter_handle": None,
        "news_keywords": ["SportOS padel court management"],
        "active": True,
    },
    "rallysight": {
        "name": "RallySight",
        "sport": ["padel", "tennis", "pickleball"],
        "tier": "direct",
        "website": "https://rallysight.com",
        "pricing_url": None,
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": None,
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["rallysight", "rally sight"],
        "twitter_handle": None,
        "news_keywords": ["RallySight sports video analytics"],
        "active": True,
    },
    "catapult_sports": {
        "name": "Catapult Sports",
        "sport": ["multi-sport"],
        "tier": "adjacent",
        "website": "https://catapultsports.com",
        "pricing_url": "https://catapultsports.com/pricing",
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": "catapult-sports",
        "greenhouse_slug": "catapult",
        "rss_feeds": ["https://www.catapultsports.com/blog/rss"],
        "reddit_mentions": ["catapult sports"],
        "twitter_handle": "CatapultSports",
        "news_keywords": ["Catapult Sports funding", "Catapult racquet analytics"],
        "active": True,
    },
    "utr_sports": {
        "name": "UTR Sports",
        "sport": ["tennis", "padel"],
        "tier": "adjacent",
        "website": "https://utrsports.net",
        "pricing_url": "https://utrsports.net/pricing",
        "app_store_id": "973706525",
        "play_store_id": None,
        "linkedin_company": "utr-sports",
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["utr sports", "UTR rating tennis"],
        "twitter_handle": "UTRSports",
        "news_keywords": ["UTR Sports tennis rating", "UTR padel"],
        "active": True,
    },
    "courtside": {
        "name": "Courtside",
        "sport": ["padel", "tennis", "pickleball"],
        "tier": "adjacent",
        "website": "https://courtside.io",
        "pricing_url": None,
        "app_store_id": None,
        "play_store_id": None,
        "linkedin_company": None,
        "greenhouse_slug": None,
        "rss_feeds": [],
        "reddit_mentions": ["courtside court management"],
        "twitter_handle": None,
        "news_keywords": ["Courtside court management sports"],
        "active": True,
    },
}

# [Company]'s own product profile (used by processors for comparison)
DREAM_PLAY_PROFILE = {
    "name": "[Company]",
    "sport": ["padel", "pickleball"],
    "positioning": (
        "AI-powered sports video intelligence platform for amateur players. "
        "D2C-first. Turns raw match footage into a scientific skill rating (Player Rating), "
        "game analysis, coaching insights, and personalised content."
    ),
    "features": [
        "dream_play_rating",         # Player Rating — scientific skill score from video
        "shot_analysis",             # Shot-by-shot breakdown
        "match_replay",              # Full match replay with annotations
        "movement_heatmaps",         # Player movement visualisation
        "rally_analysis",            # Rally-level tactical breakdown
        "coaching_insights",         # Structured improvement paths
        "highlight_generation",      # Auto-generated highlight clips
        "skill_scoring",             # Multi-dimensional TECH/TACT/PHY scores
        "matchmaking",               # Skill-based opponent matching
        "tournament_coverage",       # Tournament-level analytics
    ],
    "pricing_model": "D2C subscription",
    "tech_stack_signals": [
        "computer_vision",
        "video_ai",
        "pose_estimation",
        "ball_tracking",
        "VLM",
        "deep_learning",
    ],
}

# Helper: return only active competitors
def get_active_competitors() -> dict[str, dict]:
    return {k: v for k, v in COMPETITORS.items() if v.get("active", False)}


# Helper: filter by sport
def get_competitors_by_sport(sport: str) -> dict[str, dict]:
    return {
        k: v for k, v in COMPETITORS.items()
        if sport in v.get("sport", []) and v.get("active", False)
    }
