export type AgentTab = {
  id: string
  number: string
  name: string
  description: string
  status: AgentStatus
  href: string
  icon: string
}

export type AgentStatus =
  | 'AUTO'
  | 'HUMAN SEEDS'
  | 'ALWAYS-ON'
  | 'HUMAN APPROVES'
  | 'WEEKLY'
  | 'EVENT-TRIGGERED'

export const AGENT_TABS: AgentTab[] = [
  {
    id: 'context',
    number: '00',
    name: 'Context Input',
    description: 'Brand context, positioning, and shared brain inputs',
    status: 'HUMAN SEEDS',
    href: '/dashboard/context',
    icon: 'Database',
  },
  {
    id: 'brand-identity',
    number: '01',
    name: 'Brand Identity Studio',
    description: 'Voice engine, tagline generator, brand bible, visual moodboard',
    status: 'HUMAN SEEDS',
    href: '/dashboard/brand-identity',
    icon: 'Palette',
  },
  {
    id: 'social-content',
    number: '02',
    name: 'Social Content Studio',
    description: '30-day calendar, post generator, platform formatter across 7 content pillars',
    status: 'AUTO',
    href: '/dashboard/social-content',
    icon: 'Share2',
  },
  {
    id: 'campaign-builder',
    number: '03',
    name: 'Campaign Builder',
    description: 'Full campaign kits: copy, sequences, ad variants, KPIs',
    status: 'AUTO',
    href: '/dashboard/campaign-builder',
    icon: 'Rocket',
  },
  {
    id: 'listening',
    number: '04',
    name: 'Listening & Intelligence',
    description: 'Community pulse, trending topics, competitor tracker, opportunity queue',
    status: 'ALWAYS-ON',
    href: '/dashboard/listening',
    icon: 'Radio',
  },
  {
    id: 'influencer-crm',
    number: '05',
    name: 'Influencer & Outreach CRM',
    description: 'Relationship DB, personalised DM drafts, co-content planner',
    status: 'HUMAN APPROVES',
    href: '/dashboard/influencer-crm',
    icon: 'Users',
  },
  {
    id: 'seo-gso-content',
    number: '06',
    name: 'SEO & GSO Content Intel',
    description: 'Keyword universe, blog drafts, rank tracker, AI-search optimization',
    status: 'WEEKLY',
    href: '/dashboard/seo-gso-content',
    icon: 'Search',
  },
  {
    id: 'email-whatsapp',
    number: '07',
    name: 'Email & WhatsApp Studio',
    description: 'Segmented broadcasts, The Padel Intel newsletter, subject variants',
    status: 'AUTO',
    href: '/dashboard/email-whatsapp',
    icon: 'Mail',
  },
  {
    id: 'tournament-engine',
    number: '08',
    name: 'Tournament Engine',
    description: 'D-14 to D+1 full event sequence autogenerated',
    status: 'EVENT-TRIGGERED',
    href: '/dashboard/tournament-engine',
    icon: 'Trophy',
  },
  {
    id: 'court-partner',
    number: '09',
    name: 'Court Partner Studio',
    description: 'Intel briefs, pitch deck customiser, co-brand content, onboarding comms',
    status: 'WEEKLY',
    href: '/dashboard/court-partner',
    icon: 'Building2',
  },
  {
    id: 'analytics',
    number: '10',
    name: 'Analytics & Brand Health',
    description: 'Content performance, share of voice, sentiment score, Monday brand brief',
    status: 'AUTO',
    href: '/dashboard/analytics',
    icon: 'BarChart3',
  },
]

export const STATUS_COLORS: Record<AgentStatus, string> = {
  AUTO: 'bg-green-500/20 text-green-400 border-green-500/30',
  'HUMAN SEEDS': 'bg-orange-500/20 text-orange-400 border-orange-500/30',
  'ALWAYS-ON': 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  'HUMAN APPROVES': 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
  WEEKLY: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
  'EVENT-TRIGGERED': 'bg-red-500/20 text-red-400 border-red-500/30',
}
