from __future__ import annotations
"""
PRD generator: formats, stores, and deduplicates [Company] feature PRDs.
Posts weekly PRD summary to #ci-prds Slack channel.
"""

import json
import re
from pathlib import Path
from datetime import datetime
from outputs.slack_client import post_message, header_block, section_block, divider_block, context_block
from config.settings import settings
from db import database
from utils.diff_engine import compute_hash
from utils.logger import get_logger

logger = get_logger(__name__)


def _slugify(text: str) -> str:
    """Convert title to URL-safe slug."""
    slug = re.sub(r"[^\w\s-]", "", text.lower())
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug[:60]


def save_prd(prd: dict, week: str) -> str | None:
    """
    Save PRD to disk + database.
    Returns the file path or None on failure.
    """
    from utils.diff_engine import compute_hash

    title = prd.get("title", "Untitled Feature")
    feature_slug = prd.get("feature_slug") or _slugify(title)
    concept_summary = prd.get("concept_summary", "")
    concept_hash = compute_hash(concept_summary)

    # Create directory
    prds_dir = Path(settings.prds_dir) / week
    prds_dir.mkdir(parents=True, exist_ok=True)
    file_path = str(prds_dir / f"{feature_slug}.md")

    # Format PRD as Markdown
    md = _format_prd_markdown(prd, week)

    # Write to disk
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(md)

    # Save to DB
    try:
        database.insert_prd(
            feature_slug=feature_slug,
            title=title,
            concept_summary=concept_summary,
            concept_hash=concept_hash,
            week=week,
            file_path=file_path,
            priority_score=prd.get("priority_score"),
            effort=prd.get("effort"),
        )
        logger.info("PRD saved", title=title, week=week, path=file_path)
    except Exception as e:
        logger.error("PRD DB insert failed", title=title, error=str(e))

    return file_path


def _format_prd_markdown(prd: dict, week: str) -> str:
    """Format a PRD dict as a Markdown document."""
    lines = [
        f"# {prd.get('title', 'Untitled Feature')}",
        f"\n**Week:** {week} | **Priority:** {prd.get('priority_score', 'TBD')}/10 | **Effort:** {prd.get('effort', 'M')}\n",
        "---\n",
        "## Problem Statement\n",
        prd.get("problem_statement", ""),
        "\n## Target User Segment\n",
        prd.get("target_user_segment", ""),
        "\n## Proposed Solution\n",
        prd.get("proposed_solution", ""),
        "\n## Key User Stories\n",
    ]

    for story in prd.get("user_stories", []):
        lines.append(f"- {story}")

    lines.append("\n## Success Metrics\n")
    for metric in prd.get("success_metrics", []):
        m = metric.get("metric", "")
        t = metric.get("target", "")
        how = metric.get("measurement", "")
        lines.append(f"- **{m}**: {t}" + (f" _(measured by: {how})_" if how else ""))

    lines += [
        "\n## Technical Feasibility\n",
        prd.get("technical_feasibility", ""),
        "\n## Competitive Context\n",
        prd.get("competitive_context", ""),
    ]

    open_qs = prd.get("open_questions", [])
    if open_qs:
        lines.append("\n## Open Questions\n")
        for q in open_qs:
            lines.append(f"- {q}")

    lines += [
        "\n---\n",
        f"_Generated by [Company] CI Bot | {datetime.now().strftime('%Y-%m-%d')}_",
    ]

    return "\n".join(str(l) for l in lines)


def is_duplicate(
    proposed_concept: str,
    existing_summaries: list[dict],
    llm_client=None,
    threshold: float = 0.75,
) -> bool:
    """
    Check if proposed concept is semantically similar to any existing PRD.
    Layer 2 deduplication using LLM similarity scoring.
    """
    if not existing_summaries or not llm_client:
        return False

    summaries_text = "\n".join(
        f"- [{s.get('week', '?')}] {s.get('title', '?')}: {s.get('concept_summary', '')}"
        for s in existing_summaries[:20]
    )

    result = llm_client.complete(
        system="You are a semantic similarity judge. Compare a proposed product concept against existing PRDs.",
        user=f"""Proposed concept:
{proposed_concept}

Existing PRDs:
{summaries_text}

Is the proposed concept substantially similar (>75% overlap) to any existing PRD?
Respond with JSON: {{"is_duplicate": true/false, "most_similar_title": "...", "similarity": 0.0-1.0, "reason": "..."}}""",
        schema={
            "type": "object",
            "properties": {
                "is_duplicate": {"type": "boolean"},
                "most_similar_title": {"type": "string"},
                "similarity": {"type": "number"},
                "reason": {"type": "string"},
            },
            "required": ["is_duplicate", "similarity"],
        },
    )

    if isinstance(result, dict):
        is_dup = result.get("is_duplicate", False)
        similarity = result.get("similarity", 0.0)
        if is_dup or similarity >= threshold:
            logger.info(
                "Duplicate PRD detected",
                similar_to=result.get("most_similar_title", "?"),
                similarity=similarity,
            )
            return True

    return False


def post_weekly_prd_summary(week: str) -> bool:
    """Post a summary of this week's PRDs to #ci-prds Slack channel."""
    with database.get_db() as conn:
        rows = conn.execute(
            "SELECT * FROM prds WHERE week = ? ORDER BY priority_score DESC",
            (week,),
        ).fetchall()
        prds = [dict(r) for r in rows]

    if not prds:
        logger.info("No PRDs to post for week", week=week)
        return False

    channel = settings.slack_channel_prds or settings.slack_channel_ci
    if not channel:
        logger.warning("Slack PRD channel not configured")
        return False

    blocks = [
        header_block(f"[Company] Feature PRDs — {week}"),
        section_block(f"*{len(prds)} new feature PRDs generated this week* based on competitive intelligence and market trends."),
        divider_block(),
    ]

    for prd in prds[:5]:
        priority = prd.get("priority_score", "?")
        effort = prd.get("effort", "?")
        blocks.append(section_block(
            f"*{prd['title']}*  |  Priority: {priority}/10  |  Effort: {effort}\n"
            f"{prd.get('concept_summary', '')}\n"
            f"_Saved to: `{prd.get('file_path', 'data/prds/')}`_"
        ))
        blocks.append(divider_block())

    # Stats block
    with database.get_db() as conn:
        total_prds = conn.execute("SELECT COUNT(*) as c FROM prds").fetchone()["c"]

    blocks.append(context_block(
        f"Total PRDs in library: {total_prds} | "
        f"This week: {len(prds)} new | "
        f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M IST')}"
    ))

    ts = post_message(
        channel=channel,
        text=f"[Company] Feature PRDs — {week}",
        blocks=blocks,
    )

    if ts:
        database.track_output_sent(
            output_type="prd_summary",
            slack_channel=channel,
            message_ts=ts,
            content_hash=compute_hash(week + str(len(prds))),
        )
        # Store ts on each PRD for future reference
        with database.get_db() as conn:
            for prd in prds:
                conn.execute("UPDATE prds SET slack_ts = ? WHERE id = ?", (ts, prd["id"]))
        return True

    return False
