'use client'

import { useState } from 'react'
import { Loader2, Sparkles, History } from 'lucide-react'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { StatusBadge } from '@/components/shared/StatusBadge'
import { OutputPanel } from '@/components/shared/OutputPanel'
import { OutputHistory } from '@/components/shared/OutputHistory'
import type { GenerateResult } from '@/lib/ai'
import { getApiUrl } from '@/lib/api'

const FORMATS = ['Round Robin', 'Knockout', 'Round Robin + Knockout', 'League']
const SPORTS = ['Padel', 'Pickleball']

export default function TournamentEnginePage() {
  const [name, setName] = useState('')
  const [date, setDate] = useState('')
  const [location, setLocation] = useState('')
  const [format, setFormat] = useState('')
  const [sport, setSport] = useState('')
  const [players, setPlayers] = useState('')
  const [prize, setPrize] = useState('')
  const [extra, setExtra] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<(GenerateResult & { outputId?: string; saved?: boolean }) | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [showHistory, setShowHistory] = useState(false)
  const [historyKey, setHistoryKey] = useState(0)

  function buildPrompt(): string {
    const parts = []
    if (name) parts.push(`Tournament: ${name}`)
    if (date) parts.push(`Date: ${date}`)
    if (location) parts.push(`Location: ${location}`)
    if (sport) parts.push(`Sport: ${sport}`)
    if (format) parts.push(`Format: ${format}`)
    if (players) parts.push(`Number of players: ${players}`)
    if (prize) parts.push(`Prize/rewards: ${prize}`)
    if (extra) parts.push(`Additional context: ${extra}`)
    parts.push('\nGenerate the full D-14 to D+1 content sequence.')
    return parts.join('\n')
  }

  async function handleGenerate() {
    if (!name.trim()) return
    setLoading(true)
    setError(null)
    setResult(null)
    try {
      const res = await fetch(getApiUrl('/api/agents/tournament-engine'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: buildPrompt() }),
      })
      if (!res.ok) throw new Error((await res.json()).error ?? 'Generation failed')
      setResult(await res.json())
      setHistoryKey((k) => k + 1)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Something went wrong')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex flex-col h-full">
      <div className="px-6 py-5 border-b border-white/[0.06] gradient-header">
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-3 mb-1.5">
              <span className="text-orange-500/50 text-sm font-mono font-bold">08</span>
              <h1 className="text-white font-bold text-xl tracking-tight">Tournament Engine</h1>
              <StatusBadge status="EVENT-TRIGGERED" />
            </div>
            <p className="text-white/45 text-sm">D-14 to D+1 full event content sequence. Pre, during, and post coverage autogenerated.</p>
          </div>
          <button onClick={() => setShowHistory(!showHistory)} className="flex items-center gap-1.5 text-white/30 hover:text-white/70 text-sm transition-colors">
            <History className="w-4 h-4" /> History
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-6 space-y-5">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1.5">
            <Label className="text-white/60 text-sm">Tournament Name *</Label>
            <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Padel Slam London" className="bg-white/[0.03] border-white/[0.08] text-white placeholder:text-white/20 rounded-lg" />
          </div>
          <div className="space-y-1.5">
            <Label className="text-white/60 text-sm">Date</Label>
            <Input value={date} onChange={(e) => setDate(e.target.value)} placeholder="e.g. April 19, 2026" className="bg-white/[0.03] border-white/[0.08] text-white placeholder:text-white/20 rounded-lg" />
          </div>
          <div className="space-y-1.5">
            <Label className="text-white/60 text-sm">Location</Label>
            <Input value={location} onChange={(e) => setLocation(e.target.value)} placeholder="e.g. Canary Wharf Padel Club" className="bg-white/[0.03] border-white/[0.08] text-white placeholder:text-white/20 rounded-lg" />
          </div>
          <div className="space-y-1.5">
            <Label className="text-white/60 text-sm">Number of Players</Label>
            <Input value={players} onChange={(e) => setPlayers(e.target.value)} placeholder="e.g. 32" className="bg-white/[0.03] border-white/[0.08] text-white placeholder:text-white/20 rounded-lg" />
          </div>
          <div className="space-y-1.5">
            <Label className="text-white/60 text-sm">Sport</Label>
            <div className="flex gap-1.5">
              {SPORTS.map((s) => (
                <button key={s} onClick={() => setSport(sport === s ? '' : s)} className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${sport === s ? 'bg-orange-500/20 border-orange-500/30 text-orange-400' : 'bg-white/[0.03] border-white/[0.08] text-white/50 hover:border-white/20'}`}>{s}</button>
              ))}
            </div>
          </div>
          <div className="space-y-1.5">
            <Label className="text-white/60 text-sm">Format</Label>
            <div className="flex flex-wrap gap-1.5">
              {FORMATS.map((f) => (
                <button key={f} onClick={() => setFormat(format === f ? '' : f)} className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${format === f ? 'bg-orange-500/20 border-orange-500/30 text-orange-400' : 'bg-white/[0.03] border-white/[0.08] text-white/50 hover:border-white/20'}`}>{f}</button>
              ))}
            </div>
          </div>
        </div>

        <div className="space-y-1.5">
          <Label className="text-white/60 text-sm">Prize / Rewards</Label>
          <Textarea value={prize} onChange={(e) => setPrize(e.target.value)} placeholder="e.g. [Company] Pro memberships + trophy + Player Rating leaderboard feature" className="bg-white/[0.03] border-white/[0.08] text-white placeholder:text-white/20 min-h-[60px] resize-none rounded-xl" />
        </div>
        <div className="space-y-1.5">
          <Label className="text-white/60 text-sm">Additional Context</Label>
          <Textarea value={extra} onChange={(e) => setExtra(e.target.value)} placeholder="Sponsors, special guests, co-hosting with a court partner..." className="bg-white/[0.03] border-white/[0.08] text-white placeholder:text-white/20 min-h-[60px] resize-none rounded-xl" />
        </div>

        <button onClick={handleGenerate} disabled={loading || !name.trim()} className="btn-glow inline-flex items-center px-5 py-2.5 rounded-lg text-white font-semibold text-sm disabled:opacity-40 disabled:cursor-not-allowed disabled:shadow-none disabled:transform-none">
          {loading ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" />Generating...</> : <><Sparkles className="w-4 h-4 mr-2" />Generate Event Sequence</>}
        </button>

        {error && <div className="p-4 glass rounded-xl border-red-500/20 text-red-400 text-sm animate-slide-up">{error}</div>}

        {result && (
          <OutputPanel
            result={result}
            agentId="tournament-engine"
            label="Event Content Sequence"
            onUpdate={setResult}
          />
        )}

        {showHistory && <div className="animate-slide-up"><OutputHistory agentId="tournament-engine" refreshKey={historyKey} /></div>}
      </div>
    </div>
  )
}
